services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-odoo:19.0
    depends_on:
      - db
    ports:
      - 8069:8069
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    env_file:
      - env/odoo.env
    command: --
  db:
    image: postgres:16
    ports:
      - 5432:5432
    env_file:
      - env/postgresql.env
    volumes:
      - odoo-db-data:/var/lib/postgresql/data10
    restart: on-failure

volumes:
  odoo-web-data:
  odoo-db-data: